"""sync_schema

Revision ID: 5cc6b3a2fa92
Revises: 001
Create Date: 2026-05-03 05:52:51.586852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.encryption


# revision identifiers, used by Alembic.
revision: str = '5cc6b3a2fa92'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('commercial_register_number', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('establishment_date', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('authorized_person_name', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('contact_info', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('annual_turnover_estimate', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('contract_value', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('contract_start_date', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('contract_end_date', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('contract_type', sa.String(length=100), nullable=True))
    op.add_column('financial_reports', sa.Column('banks_data', sa.JSON(), nullable=True))
    op.add_column('financial_reports', sa.Column('collections_data', sa.JSON(), nullable=True))
    op.add_column('financial_reports', sa.Column('debts_credits_data', sa.JSON(), nullable=True))
    op.add_column('financial_reports', sa.Column('projects_data', sa.JSON(), nullable=True))
    op.add_column('financial_reports', sa.Column('activity_conditions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_reports', 'activity_conditions')
    op.drop_column('financial_reports', 'projects_data')
    op.drop_column('financial_reports', 'debts_credits_data')
    op.drop_column('financial_reports', 'collections_data')
    op.drop_column('financial_reports', 'banks_data')
    op.drop_column('companies', 'contract_type')
    op.drop_column('companies', 'contract_end_date')
    op.drop_column('companies', 'contract_start_date')
    op.drop_column('companies', 'contract_value')
    op.drop_column('companies', 'annual_turnover_estimate')
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'contact_info')
    op.drop_column('companies', 'authorized_person_name')
    op.drop_column('companies', 'establishment_date')
    op.drop_column('companies', 'commercial_register_number')
    # ### end Alembic commands ###
